# Generated by Django 5.2 on 2025-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_pollcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
